name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
  default: patch
autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
  - label: 'enhancement'
    title:
      - '/enhance/i'
  - label: 'bug'
    title:
      - '/fix/i'
    branch:
      - '/bugfix\/.+/'
  - label: 'documentation'
    files:
      - 'docs/*'
      - '*.md'
template: |
  # Release $RESOLVED_VERSION
  ## Overview
  This release includes the following categories of changes:
  $CATEGORIES

  ## Changes
  $CHANGES

  ## Contributors
  Thanks to the following people who have contributed to this release:
  $CONTRIBUTORS

  ## What's next
  Stay tuned for more updates and improvements in our upcoming releases.
